/** Auto-generated by scripts/generate-redwallet-signet-endpoints-ts.sh — do not edit. */
export const REDWALLET_SIGNET_PHONE_HOST = '192.168.1.236';
export const REDWALLET_SIGNET_BITASSETS_RPC_URL = 'http://192.168.1.236:6004';
export const REDWALLET_SIGNET_BITASSETS_QUIC_URL = '192.168.1.236:6104';
