/** Auto-generated by scripts/generate-redwallet-signet-endpoints-ts.sh — do not edit. */
export const REDWALLET_SIGNET_PHONE_HOST: string = '192.168.1.236';
export const REDWALLET_SIGNET_BITASSETS_RPC_URL: string = 'http://192.168.1.236:6004';
export const REDWALLET_SIGNET_BITASSETS_QUIC_URL: string = '192.168.1.236:6104';
