// LayerTwo-Labs EDSL conformance — generated by picolisppilog Generated.RepoTargetEmit (Node)
// Regenerate: pil main.l (from picolisppilog/)

const REPO_NAME = 'redwallet';
const JENKINS_CMD_TAG = '__AUTO_NODE__';

import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { TextEncoder, TextDecoder } from 'node:util';

// --- Mocks and Resolve Interception to load React Native files in Node ---
const mockDir = '/tmp/redwallet-mocks';
if (!fs.existsSync(mockDir)) fs.mkdirSync(mockDir);

fs.writeFileSync(path.join(mockDir, 'react-native.js'), `export const Platform = { OS: 'ios' }; export const TurboModuleRegistry = { get: () => ({}) };`);
fs.writeFileSync(path.join(mockDir, 'react-native-keychain.js'), `export const getGenericPassword = () => Promise.resolve(false); export const setGenericPassword = () => Promise.resolve(); export const resetGenericPassword = () => Promise.resolve();`);
fs.writeFileSync(path.join(mockDir, 'react-native-device-info.js'), `export const isEmulatorSync = () => false; export const isTablet = () => false; export const getDeviceType = () => 'Handset';`);
fs.writeFileSync(path.join(mockDir, 'react-native-fs.js'), `export const CachesDirectoryPath = '/tmp'; export const DocumentDirectoryPath = '/tmp';`);
fs.writeFileSync(path.join(mockDir, 'react-native-default-preference.js'), `export const setName = () => {}; export const get = () => Promise.resolve(""); export const set = () => Promise.resolve();`);
fs.writeFileSync(path.join(mockDir, 'realm.js'), `export const open = () => Promise.resolve({});`);
fs.writeFileSync(path.join(mockDir, 'react-native-localize.js'), `export const getLocales = () => [{ languageCode: 'en' }]; export const getCountry = () => 'US';`);
fs.writeFileSync(path.join(mockDir, 'react-native-haptic-feedback.js'), `export const trigger = () => {};`);
fs.writeFileSync(path.join(mockDir, 'react-native-share.js'), `export const open = () => Promise.resolve();`);

import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const Module = require('module');
const originalResolve = Module._resolveFilename;
Module._resolveFilename = function (request) {
  const mocks = {
    'react-native': 'react-native.js',
    'react-native-keychain': 'react-native-keychain.js',
    'react-native-device-info': 'react-native-device-info.js',
    'react-native-fs': 'react-native-fs.js',
    'react-native-default-preference': 'react-native-default-preference.js',
    'realm': 'realm.js',
    'react-native-localize': 'react-native-localize.js',
    'react-native-haptic-feedback': 'react-native-haptic-feedback.js',
    'react-native-share': 'react-native-share.js'
  };
  for (const [name, filename] of Object.entries(mocks)) {
    if (request === name || request.includes('/node_modules/' + name + '/')) {
      return path.join(mockDir, filename);
    }
  }
  return originalResolve.apply(this, arguments);
};

const babel = require('@babel/core');
const moduleCache = new Map();

function customRequire(modulePath, referrerDir) {
  if (!modulePath.startsWith('.') && !modulePath.startsWith('/')) {
    if (['react-native', 'react-native-keychain', 'react-native-device-info', 'react-native-fs', 'react-native-default-preference', 'realm', 'react-native-localize', 'react-native-haptic-feedback', 'react-native-share'].includes(modulePath)) {
      return require(modulePath);
    }
    return require(path.resolve('.', 'node_modules', modulePath));
  }
  const absolutePath = resolveModulePath(path.resolve(referrerDir, modulePath));
  if (absolutePath.endsWith('/blue-app.ts') || absolutePath.endsWith('/blue-app.js') || absolutePath.endsWith('/blue-app')) {
    return {};
  }
  if (absolutePath.endsWith('/class/index.ts') || absolutePath.endsWith('/class/index.js') || absolutePath.endsWith('/class/index') || absolutePath.endsWith('/class')) {
    const bitcoin = require(path.resolve('.', 'node_modules', 'bitcoinjs-lib'));
    const getNetwork = customRequire('./models/network', '.').getNetwork;
    const hexToUint8Array = customRequire('./blue_modules/uint8array-extras', '.').hexToUint8Array;
    class MockLegacyWallet {
      static scriptPubKeyToAddress(scriptPubKey) {
        try {
          const scriptPubKey2 = hexToUint8Array(scriptPubKey);
          return bitcoin.payments.p2pkh({
            output: scriptPubKey2,
            network: getNetwork(),
          }).address || false;
        } catch (_) {
          return false;
        }
      }
    }
    return {
      LegacyWallet: MockLegacyWallet,
      HDSegwitBech32Wallet: class {},
      SegwitBech32Wallet: class {},
      SegwitP2SHWallet: class {},
      TaprootWallet: class {},
      AbstractWallet: class {},
      BitAssetsWallet: class { static type = "bitassetsWallet"; }
    };
  }
  if (moduleCache.has(absolutePath)) {
    return moduleCache.get(absolutePath).exports;
  }
  const moduleObj = { exports: {} };
  moduleCache.set(absolutePath, moduleObj);
  let fileContent = fs.readFileSync(absolutePath, 'utf8');
  if (absolutePath.endsWith('bitassets-wallet.ts')) {
    fileContent = fileContent.replace(/export class BitAssetsWallet[\\s\\S]+?hasBitAssetsWallet/, 'export class BitAssetsWallet { static type = "bitassetsWallet"; }\\nexport function hasBitAssetsWallet');
  }
  const compiled = babel.transformSync(fileContent, {
    presets: ['module:@react-native/babel-preset'],
    filename: absolutePath
  }).code;
  const moduleDir = path.dirname(absolutePath);
  const sandbox = {
    console, process, Object, Array, String, Number, Boolean, Date, RegExp, Error, Promise, URL, Uint8Array, TextEncoder, TextDecoder, __DEV__: false,
    globalThis: { __DEV__: false },
    require: (p) => customRequire(p, moduleDir),
    module: moduleObj,
    exports: moduleObj.exports
  };
  sandbox.globalThis = sandbox;
  const context = vm.createContext(sandbox);
  vm.runInContext(compiled, context, { filename: absolutePath });
  return moduleObj.exports;
}

function resolveModulePath(basePath) {
  const extensions = ['.ts', '.tsx', '.js', '.jsx', '.json'];
  if (fs.existsSync(basePath) && fs.statSync(basePath).isFile()) return basePath;
  for (const ext of extensions) { if (fs.existsSync(basePath + ext)) return basePath + ext; }
  for (const ext of extensions) {
    const indexFile = path.join(basePath, 'index' + ext);
    if (fs.existsSync(indexFile)) return indexFile;
  }
  throw new Error('Cannot resolve module: ' + basePath);
}

const utilFunctions = customRequire('./util/isValidBech32Address', '.');
const bitassetsFunctions = customRequire('./class/wallets/bitassets-wallet', '.');
const electrumFunctions = customRequire('./blue_modules/BlueElectrum', '.');

const realFns = {
  isValidBech32Address: utilFunctions.isValidBech32Address,
  combinePSBTs: customRequire('./util/combinePSBTs', '.').combinePSBTs,
  normalizeBitAssetsRpcUrlForRuntime: bitassetsFunctions.normalizeBitAssetsRpcUrlForRuntime,
  normalizeBitAssetsLiteWalletQuicUrlForRuntime: bitassetsFunctions.normalizeBitAssetsLiteWalletQuicUrlForRuntime,
  hasBitAssetsWallet: bitassetsFunctions.hasBitAssetsWallet,
  getHardcodedPeersForCurrentNetwork: electrumFunctions.getHardcodedPeersForCurrentNetwork,
  getSuggestedServersForCurrentNetwork: electrumFunctions.getSuggestedServersForCurrentNetwork
};

const jsKnownCallsWithInfo = [
  ['isValidBech32Address', {ciPure: true, ciCost: 8, ciIdempotent: true, ciCommutesWithLog: true}],
  ['normalizeBitAssetsRpcUrlForRuntime', {ciPure: true, ciCost: 12, ciIdempotent: true, ciCommutesWithLog: true}],
  ['normalizeBitAssetsLiteWalletQuicUrlForRuntime', {ciPure: true, ciCost: 12, ciIdempotent: true, ciCommutesWithLog: true}],
  ['hasBitAssetsWallet', {ciPure: true, ciCost: 5, ciIdempotent: true, ciCommutesWithLog: true}],
  ['getHardcodedPeersForCurrentNetwork', {ciPure: true, ciCost: 10, ciIdempotent: true, ciCommutesWithLog: true}],
  ['getSuggestedServersForCurrentNetwork', {ciPure: true, ciCost: 10, ciIdempotent: true, ciCommutesWithLog: true}],
  ['combinePSBTs', {ciPure: false, ciCost: 120, ciIdempotent: false, ciCommutesWithLog: true}]
];

const jsCallRuleSchemas = [
  { schemaName: 'idempotence', when: (info) => info.ciIdempotent, rulesFor: (name) => [ { lhs: ['call', name, ['call', name, 'x']], rhs: ['call', name, 'x'] } ] },
  { schemaName: 'pure-call-cse', when: (info) => info.ciPure, rulesFor: (name) => [ { lhs: ['if', 'c', ['call', name, 'a'], ['call', name, 'a']], rhs: ['call', name, 'a'] }, { lhs: ['if', 'c', ['call', name, 'x'], ['call', name, 'x']], rhs: ['call', name, 'x'] } ] },
  { schemaName: 'log-commutes-with-call', when: (info) => info.ciCommutesWithLog, rulesFor: (name) => [ { lhs: ['log', 'm', ['call', name, 'a']], rhs: ['call', name, ['log', 'm', 'a']] } ] }
];

function repoContainsNeedle(needle) {
  const skip = new Set(['.git', 'node_modules', 'target', 'dist', 'build']);
  const exts = new Set(['.rs', '.js', '.mjs', '.ts', '.tsx', '.json', '.toml', '.py', '.go', '.md']);
  function walk(dir) {
    for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
      if (skip.has(ent.name)) continue;
      const p = path.join(dir, ent.name);
      if (ent.isDirectory()) { if (walk(p)) return true; continue; }
      if (![...exts].some((e) => ent.name.endsWith(e))) continue;
      const body = fs.readFileSync(p, 'utf8');
      if (body.includes(needle)) return true;
    }
    return false;
  }
  return walk('.');
}

test('edsl_package_json_present', () => {
  assert.ok(fs.existsSync('package.json'));
});

test('edsl_repo_registered', () => {
  assert.equal(REPO_NAME, 'redwallet');
  assert.equal(JENKINS_CMD_TAG, '__AUTO_NODE__');
});

test('edsl_snippet_0_package_json', () => {
  const needle = '"name"';
  assert.ok(repoContainsNeedle(needle), 'expected repo source to contain: ' + 'package_json');
});

test('edsl_snippet_1_repo_name', () => {
  const needle = 'redwallet';
  assert.ok(repoContainsNeedle(needle), 'expected repo source to contain: ' + 'repo_name');
});


function makeRealCall(realFns) { return (name, arg) => { if (realFns[name]) return realFns[name](arg); throw new Error('no real fn ' + name); }; }
function runExpr(expr, realCall, logs) {
  if (expr == null || typeof expr !== 'object') return expr;
  if (expr.tag === 'if') { const c = runExpr(expr.cond, realCall, logs); return runExpr(c ? expr.then : expr.else, realCall, logs); }
  if (expr.tag === 'log') { logs.push(expr.msg); return runExpr(expr.body, realCall, logs); }
  if (expr.tag === 'call') { const v = runExpr(expr.arg, realCall, logs); return realCall(expr.name, v); }
  return expr; }
function jsHeggSaturate(expr) {
  if (!expr || typeof expr !== 'object') return expr;
  const name = expr.name;
  const info = (jsKnownCallsWithInfo.find(([n]) => n === expr.name) || [null, {}])[1];
  if (expr.tag === 'call') {
    const inner = jsHeggSaturate(expr.arg);
    for (const schema of jsCallRuleSchemas) {
      if (schema.when(info)) {
        for (const rw of schema.rulesFor(expr.name)) {
          if (matchesPattern(inner, rw.lhs, expr.name)) return buildReplacement(rw.rhs, expr.name, inner);
        }
      }
    }
    if (name === 'isValidBech32Address' && inner.tag === 'call' && inner.name === 'isValidBech32Address') return { tag: 'call', name: 'isValidBech32Address', arg: inner.arg };
    if (name === 'normalizeBitAssetsRpcUrlForRuntime' && inner.tag === 'call' && inner.name === 'normalizeBitAssetsRpcUrlForRuntime') return { tag: 'call', name: 'normalizeBitAssetsRpcUrlForRuntime', arg: inner.arg };
    return { tag: 'call', name: expr.name, arg: inner };
  }
  if (expr.tag === 'if') {
    const c = jsHeggSaturate(expr.cond);
    const t = jsHeggSaturate(expr.then);
    const e = jsHeggSaturate(expr.else);
    if (c === true || c === 'true') return t;
    if (c === false || c === 'false') return e;
    if (t.tag === 'call' && e.tag === 'call' && t.name === e.name && (jsKnownCallsWithInfo.find(([n]) => n === t.name) || [null, {}])[1].ciPure) return t;
    return { tag: 'if', cond: c, then: t, else: e };
  }
  if (expr.tag === 'log') {
    return { tag: 'log', msg: expr.msg, body: jsHeggSaturate(expr.body) };
  }
  return expr;
}
function matchesPattern(expr, pat, name) {
  if (Array.isArray(pat)) {
    if (pat[0] === 'call' && expr.tag === 'call' && (pat[1] === name || pat[1] === expr.name) ) return matchesPattern(expr.arg, pat[2], name);
    if (pat[0] === 'if' && expr.tag === 'if') return matchesPattern(expr.cond, pat[1], name) && matchesPattern(expr.then, pat[2], name) && matchesPattern(expr.else, pat[3], name);
  }
  return pat === 'x' || pat === 'a' || pat === 'c' || pat === expr;
}
function buildReplacement(pat, name, inner) {
  if (Array.isArray(pat)) {
    if (pat[0] === 'call') return { tag: 'call', name: pat[1] === name ? name : pat[1], arg: buildReplacement(pat[2], name, inner) };
  }
  return pat === 'x' || pat === 'a' ? inner : pat;
}
function runBothAndCompare(buildTree, realFns, name) {
  const realCall = makeRealCall(realFns);
  const original = buildTree();
  const saturated = jsHeggSaturate(original);
  const logs1 = []; const r1 = runExpr(original, realCall, logs1);
  const logs2 = []; const r2 = runExpr(saturated, realCall, logs2);
  assert.deepStrictEqual(logs1, logs2, name + ' logs must match after hegg');
  assert.deepStrictEqual(r1, r2, name + ' result must match after hegg');
}

// --- Real ECall hegg confluence proofs for redwallet ---
test('real_ecall_isValidBech32Address_idempotent', () => {
  runBothAndCompare(() => ({tag:'call', name:'isValidBech32Address', arg: {tag:'call', name:'isValidBech32Address', arg: 'bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh'}}), realFns, 'isValidBech32Address_idem');
});
test('real_ecall_normalizeBitAssetsRpcUrlForRuntime_idempotent', () => {
  runBothAndCompare(() => ({tag:'call', name:'normalizeBitAssetsRpcUrlForRuntime', arg: {tag:'call', name:'normalizeBitAssetsRpcUrlForRuntime', arg: 'http://127.0.0.1:8080'}}), realFns, 'normalizeBitAssetsRpcUrl_idem');
});
test('real_ecall_hasBitAssetsWallet_idempotent', () => {
  runBothAndCompare(() => ({tag:'call', name:'hasBitAssetsWallet', arg: {tag:'call', name:'hasBitAssetsWallet', arg: []}}), realFns, 'hasBitAssetsWallet_idem');
});
