#!/usr/bin/env bash
# Emit helpers/redwalletSignetEndpoints.generated.ts from redwallet-signet-endpoints.sh.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT_DIR/helpers/redwalletSignetEndpoints.generated.ts"
LOG_ROOT="${REDWALLET_LOG_ROOT:-/Volumes/T705/redwallet-logs}"

# Real-device bundles must match Mac LAN RPC (not Tailscale-first default from signet-endpoints).
MAC_LAN_IP="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)"
MAC_RPC="${REDWALLET_BITASSETS_RPC_MAC:-http://${MAC_LAN_IP:-192.168.1.50}:6004}"
PHONE_HOST="${REDWALLET_PHONE_HOST:-${MAC_RPC#http://}}"
PHONE_HOST="${PHONE_HOST#https://}"
PHONE_HOST="${PHONE_HOST%%/*}"
PHONE_HOST="${PHONE_HOST%%:*}"
export REDWALLET_PHONE_HOST="$PHONE_HOST"

bash "$ROOT_DIR/scripts/redwallet-signet-endpoints.sh" >/dev/null
ENV_FILE="$(ls -t "$LOG_ROOT"/signet-endpoints-*/redwallet-signet.env 2>/dev/null | head -1 || true)"
if [[ -z "$ENV_FILE" || ! -f "$ENV_FILE" ]]; then
  echo "BLOCKER missing signet-endpoints env under $LOG_ROOT" >&2
  exit 1
fi
# shellcheck disable=SC1090
source "$ENV_FILE"

PHONE_HOST="${REDWALLET_PHONE_HOST:?REDWALLET_PHONE_HOST unset in $ENV_FILE}"
RPC_URL="${BITASSETS_RPC_URL:?BITASSETS_RPC_URL unset in $ENV_FILE}"
RPC_HOST="${RPC_URL#http://}"
RPC_HOST="${RPC_HOST#https://}"
RPC_HOST="${RPC_HOST%%/*}"
QUIC_HOST="${RPC_HOST%%:*}"
QUIC_PORT="${BITASSETS_LITE_WALLET_QUIC_PORT:-6104}"

cat >"$OUT" <<EOF
/** Auto-generated by scripts/generate-redwallet-signet-endpoints-ts.sh — do not edit. */
export const REDWALLET_SIGNET_PHONE_HOST: string = '${PHONE_HOST}';
export const REDWALLET_SIGNET_BITASSETS_RPC_URL: string = '${RPC_URL}';
export const REDWALLET_SIGNET_BITASSETS_QUIC_URL: string = '${QUIC_HOST}:${QUIC_PORT}';
EOF

echo "wrote $OUT phone_host=$PHONE_HOST rpc=$RPC_URL"
