#!/usr/bin/env bash
# Canonical post-PASS path: transfer-only on Android after a successful register.
# Sets wallet ID gates, MONITOR_NO_RESTART, and delegates to the phone-chain script.
# Wallet restore before re-run: docs/orchestration/ANDROID_WALLET_RESTORE.md
# Full reserve→register→transfer: redwallet-android-phone-chain-reserve-register.sh
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERIAL="${1:-${ANDROID_SERIAL:-${REDWALLET_ANDROID_SERIAL:-0A201JECB03306}}}"

export ANDROID_SERIAL="$SERIAL"
export REDWALLET_ANDROID_SERIAL="$SERIAL"
export REDWALLET_LIPHONE_STANDBY=1
export REDWALLET_CHAIN_TRANSFER_ONLY=1
export REDWALLET_ANDROID_MONITOR_NO_RESTART=1
export REDWALLET_ANDROID_SKIP_LAUNCH=0
export REDWALLET_CHAIN_POLL_SEC="${REDWALLET_CHAIN_POLL_SEC:-5}"
export REDWALLET_CHAIN_POLLS="${REDWALLET_CHAIN_POLLS:-30}"
export REDWALLET_CHAIN_TRANSFER_DELAY_SEC="${REDWALLET_CHAIN_TRANSFER_DELAY_SEC:-20}"

CHAIN_ASSET="${REDWALLET_CHAIN_ASSET:-RWFLEET20260527-130941}"
export REDWALLET_CHAIN_ASSET="$CHAIN_ASSET"
export REDWALLET_CHAIN_REGISTER_TXID="${REDWALLET_CHAIN_REGISTER_TXID:-7103eccf39637e5ebbfae2f0d5edf054bf26c2b87ce18f2d2ec3a2be2d0de689}"
export REDWALLET_BITASSETS_TRANSFER_ASSET_ID="${REDWALLET_BITASSETS_TRANSFER_ASSET_ID:-031f96aec2507050d099980354ae66434da0dda949297dedef49750c23a07b99}"
# Registering wallet from 20260527-133421 collector (required to spend RWFLEET20260527-130941).
export REDWALLET_BITASSETS_WALLET_ID="${REDWALLET_BITASSETS_WALLET_ID:-1608e006e3fc6953f45ee7361a28ae9790c34124e4ef64f3d5d6438240d5bf1e}"
export REDWALLET_ANDROID_REQUIRE_WALLET_ID="${REDWALLET_ANDROID_REQUIRE_WALLET_ID:-1}"
export REDWALLET_ANDROID_EXPECT_BITASSETS_WALLET_COUNT="${REDWALLET_ANDROID_EXPECT_BITASSETS_WALLET_COUNT:-1}"

echo "GUARDED_TRANSFER_START asset=$CHAIN_ASSET register_txid=${REDWALLET_CHAIN_REGISTER_TXID} wallet_id=${REDWALLET_BITASSETS_WALLET_ID}"
exec bash "$ROOT_DIR/scripts/redwallet-android-phone-chain-reserve-register.sh" "$SERIAL"
